kumuluzee:
  name: sistem-porocil
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
integrations:
  sistem-porocil:
    base-url: https://covid-193.p.rapidapi.com/history?country=Slovenia&